SELECT   
         Matricula,
		 -- CALCULA DIFERENÇA DE DIAS ENTRE UMA DATA 
		 DATEDIFF(DAY, Data, DATASAIDA) AS DIAS,
         -- (CONVERT(VARCHAR, DATEDIFF(MI, CONVERT(DATETIME, CONVERT(VARCHAR(10), HORA, 108)) , HoraSaida) / 60)+':'+ 
          -- CONVERT(VARCHAR, DATEDIFF(MI, CONVERT(DATETIME, CONVERT(VARCHAR(10), HORA, 108)) , HoraSaida) % 60)) AS HORAS,
		 --  CONVERT(VARCHAR, DATASAIDA, 110)+' '+
		  -- CONVERT(VARCHAR, HORASAIDA, 108) AS HORASAIDA,
--CALCULA A DIFERENÇA DE HORAS ENTRE A ENTRADA E A SAIDA DO PACIENTE INTERNADO NO PS
CONVERT(VARCHAR,DATEDIFF(MI, CONVERT(DATETIME, (CONVERT(VARCHAR, DATA, 110)+' '+ CONVERT(VARCHAR, HORA, 108) )), 
CONVERT(DATETIME, (CONVERT(VARCHAR, DATASAIDA, 110)+' '+ CONVERT(VARCHAR, HORASAIDA, 108) ))) /60)+':'+         
CONVERT(VARCHAR,DATEDIFF(MI, CONVERT(DATETIME, (CONVERT(VARCHAR, DATA, 110)+' '+ CONVERT(VARCHAR, HORA, 108) )), 
CONVERT(DATETIME, (CONVERT(VARCHAR, DATASAIDA, 110)+' '+ CONVERT(VARCHAR, HORASAIDA, 108) ))) %60) AS HORA_CERTA,  
CONVERT(VARCHAR,Data, 103) AS DataEntrada, CONVERT(VARCHAR,hora, 108) AS HoraEntrada , CONVERT(VARCHAR,DataSaida, 103) AS DataSaida, CONVERT(VARCHAR,HoraSaida, 108) AS HoraSaida
FROM          PACIENTE_CadastroDasConsultas
WHERE        (AtendidoNoPA = - 1) AND (Data BETWEEN '2015-09-01' AND '2015-09-30') AND
(DATEDIFF(DAY, Data, DATASAIDA)> 0) AND
(CONVERT(INT, CONVERT(VARCHAR,DATEDIFF(MI, CONVERT(DATETIME, (CONVERT(VARCHAR, DATA, 110)+' '+ CONVERT(VARCHAR, HORA, 108) )), 
CONVERT(DATETIME, (CONVERT(VARCHAR, DATASAIDA, 110)+' '+ CONVERT(VARCHAR, HORASAIDA, 108) ))) /60)) >=24)
ORDER BY DATEDIFF(DAY, Data, DATASAIDA), DATA;

SELECT   
    COUNT(*) AS Total
FROM          PACIENTE_CadastroDasConsultas
WHERE        (AtendidoNoPA = - 1) AND (Data BETWEEN '2015-09-1' AND '2015-09-30') AND
(CONVERT(INT, CONVERT(VARCHAR,DATEDIFF(MI, CONVERT(DATETIME, (CONVERT(VARCHAR, DATA, 110)+' '+ CONVERT(VARCHAR, HORA, 108) )), 
CONVERT(DATETIME, (CONVERT(VARCHAR, DATASAIDA, 110)+' '+ CONVERT(VARCHAR, HORASAIDA, 108) ))) /60)) >=24)

SELECT
    COUNT(*) AS Total,   
    sum(convert(int, DATEDIFF(DAY, Data, DATASAIDA))) AS Total_Dias,
	convert(real, sum(convert(int, DATEDIFF(DAY, Data, DATASAIDA))) / COUNT(*)) as media
FROM          PACIENTE_CadastroDasConsultas
WHERE        (AtendidoNoPA = - 1) AND (Data BETWEEN '2015-09-1' AND '2015-09-30') AND 
(CONVERT(INT, CONVERT(VARCHAR,DATEDIFF(MI, CONVERT(DATETIME, (CONVERT(VARCHAR, DATA, 110)+' '+ CONVERT(VARCHAR, HORA, 108) )), 
CONVERT(DATETIME, (CONVERT(VARCHAR, DATASAIDA, 110)+' '+ CONVERT(VARCHAR, HORASAIDA, 108) ))) /60)) >=24)



SELECT        FK_MATRICULA, DATA_PONTO, ENTRADA_01, SAIDA_01, ENTRADA_02, ENTRADA_03, SAIDA_03, ST_PONTO, HORA_PONTO, FK_SETOR, OBS, SAIDA_02
FROM            GCP_EXTRATO_PONTO
WHERE        (FK_MATRICULA = '86138') AND (DATA_PONTO >= CONVERT(DATETIME, '2017-03-01 00:00:00', 102))